name: Deploy Mautic to DigitalOcean

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      vps_name:
        description: 'VPS Name'
        required: false
        default: ''
      vps_size:
        description: 'VPS Size'
        required: false
        default: 's-2vcpu-2gb'
        type: choice
        options:
          - 's-1vcpu-1gb'
          - 's-2vcpu-2gb'
          - 's-2vcpu-4gb'
          - 's-4vcpu-8gb'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Mautic
      uses: escopecz/mautic-do-action@0.0.0
      with:
        vps-name: ${{ github.event.inputs.vps_name || vars.VPS_NAME || format('mautic-{0}', github.ref_name) }}
        vps-size: ${{ github.event.inputs.vps_size || 's-2vcpu-2gb' }}
        vps-region: 'nyc1'
        domain: ${{ vars.DOMAIN || '' }}
        email: ${{ vars.EMAIL_ADDRESS }}
        mautic-password: ${{ secrets.MAUTIC_PASSWORD }}
        mysql-password: ${{ secrets.MYSQL_PASSWORD || secrets.MAUTIC_PASSWORD }}
        mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD || secrets.MAUTIC_PASSWORD }}
        digitalocean-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        mautic-port: '8001'